### ISSUE TITLE
Roadmap for stable release

### ISSUE THREAD

**Issue by YerkoPalma** [YerkoPalma/choo-audio#1]
Just a list of things to do before publishing a 1.0.0 version

- [x] Load from url or ArrayBuffer
- [x] Play/pause/stop
- [x] Set volume
- [x] Set filter
- [x] Record
- [x] ~Download~ record audio
- Mix audio (equal power crossfade)_*_
- ~Set position and orientation (panner)~
- ~Compression~ 
- [x] Clear list
- [x] Need a 'Load complete' event
- [x] Need a 'Record complete' event
- ~Improve 'Add node' event - add control over node position~
- ~Convolution and Procesor (not quite sure about those)~
- [x] Example
- [x] Documentation
